### ISSUE TITLE
Todo: Branding/Style decisions

### ISSUE THREAD

**Issue by kevinzweerink** [agendae/agendae.github.io#1]
- [x] Decide brand colors
- [x] Decide data scale
- [x] Pick typography
- [x] Establish separation of data, content, interface
- [x] Colors work on dark or light bg

**Comment by kevinzweerink** [comment]
![style-01](https://cloud.githubusercontent.com/assets/3193536/6229073/ba7d34f2-b681-11e4-8d01-4e43063c0387.png)
![style-02](https://cloud.githubusercontent.com/assets/3193536/6229074/ba7ffe12-b681-11e4-953c-8b9fcf6e6e6d.png)
